name: CI

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        lua_version: [5.1, 5.2, 5.3, 5.4]
        include:
          - lua_version: luajit
            os: ubuntu-latest
        exclude:
          # Exclude some combinations to reduce CI time
          - os: windows-latest
            lua_version: 5.1
          - os: windows-latest
            lua_version: 5.2
          - os: macos-latest
            lua_version: 5.1

    steps:
    - uses: actions/checkout@v4

    - name: Set up Lua
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: ${{ matrix.lua_version }}

    - name: Set up Luarocks
      uses: leafo/gh-actions-luarocks@v4

    - name: Install dependencies
      run: |
        luarocks install luafilesystem
        luarocks install argparse
        if [ "${{ matrix.lua_version }}" != "5.1" ] && [ "${{ matrix.lua_version }}" != "luajit" ]; then
          luarocks install lanes
        fi
      shell: bash

    - name: Build
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          make windows
        else
          make
        fi
      shell: bash

    - name: Run tests
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          make test_windows
        else
          make test
        fi
      shell: bash

    - name: Test ks language support
      if: matrix.lua_version == '5.3'
      run: |
        cd test
        lua test_ks_simple.lua
      shell: bash

    - name: Run luacheck on itself
      run: |
        ./bin/luacheck src/
        ./bin/luacheck spec/
        ./bin/luacheck test/ --ignore 211
      shell: bash