name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        lua_version: [5.1, 5.2, 5.3, 5.4]
        exclude:
          # Exclude some combinations to reduce build time
          - os: windows-latest
            lua_version: 5.1
          - os: windows-latest
            lua_version: 5.2
          - os: macos-latest
            lua_version: 5.1

    steps:
    - uses: actions/checkout@v4

    - name: Set up Lua
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: ${{ matrix.lua_version }}

    - name: Set up Luarocks
      uses: leafo/gh-actions-luarocks@v4

    - name: Install dependencies
      run: |
        luarocks install luafilesystem
        luarocks install argparse
        luarocks install lanes  # For multithreading support

    - name: Build
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          make windows
        else
          make
        fi
      shell: bash

    - name: Run tests
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          make test_windows
        else
          make test
        fi
      shell: bash

    - name: Test ks language support
      if: matrix.lua_version == '5.3'
      run: |
        cd test
        lua test_ks_comprehensive.lua
      shell: bash

    - name: Create package
      run: |
        make package
      shell: bash

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: luacheck-${{ matrix.os }}-lua${{ matrix.lua_version }}
        path: |
          bin/luacheck
          bin/luacheck.exe
          luacheck-*.rockspec
          build/

  create-release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Set up environment
      run: |
        echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        echo "RELEASE_NAME=Luacheck $TAG_NAME" >> $GITHUB_ENV

    - name: Create release directory
      run: |
        mkdir -p release
        cp README.md release/
        cp CHANGELOG.md release/
        cp LICENSE release/
        cp -r bin/ release/
        cp -r test/ release/

    - name: Create Linux binary package
      run: |
        cd release
        tar -czf luacheck-${{ env.TAG_NAME }}-linux-x86_64.tar.gz bin/luacheck README.md CHANGELOG.md LICENSE

    - name: Create Windows binary package
      run: |
        cd release
        zip -r luacheck-${{ env.TAG_NAME }}-windows-x86_64.zip bin/luacheck.exe README.md CHANGELOG.md LICENSE

    - name: Create macOS binary package
      run: |
        cd release
        tar -czf luacheck-${{ env.TAG_NAME }}-macos-x86_64.tar.gz bin/luacheck README.md CHANGELOG.md LICENSE

    - name: Create source package
      run: |
        cd release
        tar -czf luacheck-${{ env.TAG_NAME }}-source.tar.gz README.md CHANGELOG.md LICENSE src/ test/ docsrc/ scripts/ spec/

    - name: Create rockspec package
      run: |
        cp *.rockspec release/

    - name: Create release notes
      run: |
        echo "# Luacheck ${{ env.TAG_NAME }}" > release_notes.md
        echo "" >> release_notes.md
        echo "## Changes" >> release_notes.md
        echo "" >> release_notes.md
        echo "See [CHANGELOG.md](CHANGELOG.md) for detailed changes." >> release_notes.md
        echo "" >> release_notes.md
        echo "## Downloads" >> release_notes.md
        echo "" >> release_notes.md
        echo "### Binaries" >> release_notes.md
        echo "- [Linux x86_64](luacheck-${{ env.TAG_NAME }}-linux-x86_64.tar.gz)" >> release_notes.md
        echo "- [Windows x86_64](luacheck-${{ env.TAG_NAME }}-windows-x86_64.zip)" >> release_notes.md
        echo "- [macOS x86_64](luacheck-${{ env.TAG_NAME }}-macos-x86_64.tar.gz)" >> release_notes.md
        echo "" >> release_notes.md
        echo "### Source" >> release_notes.md
        echo "- [Source tarball](luacheck-${{ env.TAG_NAME }}-source.tar.gz)" >> release_notes.md
        echo "- [Luarocks package](luacheck-${{ env.TAG_NAME }}-1.rockspec)" >> release_notes.md
        echo "" >> release_notes.md
        echo "## Installation" >> release_notes.md
        echo "" >> release_notes.md
        echo "### From binaries" >> release_notes.md
        echo '```bash' >> release_notes.md
        echo '# Download and extract the binary for your platform' >> release_notes.md
        echo '# Then add to your PATH' >> release_notes.md
        echo '```' >> release_notes.md
        echo "" >> release_notes.md
        echo "### From Luarocks" >> release_notes.md
        echo '```bash' >> release_notes.md
        echo 'luarocks install luacheck' >> release_notes.md
        echo '```' >> release_notes.md
        echo "" >> release_notes.md
        echo "### From source" >> release_notes.md
        echo '```bash' >> release_notes.md
        echo 'make && make install' >> release_notes.md
        echo '```' >> release_notes.md

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.TAG_NAME }}
        name: ${{ env.RELEASE_NAME }}
        body_path: release_notes.md
        draft: false
        prerelease: contains(env.TAG_NAME, '-')
        files: |
          release/luacheck-${{ env.TAG_NAME }}-linux-x86_64.tar.gz
          release/luacheck-${{ env.TAG_NAME }}-windows-x86_64.zip
          release/luacheck-${{ env.TAG_NAME }}-macos-x86_64.tar.gz
          release/luacheck-${{ env.TAG_NAME }}-source.tar.gz
          release/*.rockspec
          release/README.md
          release/CHANGELOG.md
          release/LICENSE
        generate_release_notes: true

    - name: Publish to Luarocks
      run: |
        # This step would require Luarocks API keys
        echo "Luarocks publishing would happen here"
        echo "luarocks upload luacheck-${{ env.TAG_NAME }}-1.rockspec --api-key=\$LUAROCKS_API_KEY"
      env:
        LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
      if: env.LUAROCKS_API_KEY != ''

  notify:
    needs: create-release
    runs-on: ubuntu-latest
    if: success() && startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Send success notification
      run: |
        echo "Release ${{ env.TAG_NAME }} created successfully!"
        echo "Release URL: ${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ env.TAG_NAME }}"
      env:
        TAG_NAME: ${{ github.ref#refs/tags/v }}

  rollback:
    needs: create-release
    runs-on: ubuntu-latest
    if: failure() && startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Send failure notification
      run: |
        echo "Release creation failed for ${{ env.TAG_NAME }}"
        echo "Please check the logs and manually create the release if needed"
      env:
        TAG_NAME: ${{ github.ref#refs/tags/v }}